# Generated by Django 3.1.1 on 2020-09-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('same_point_connection_rate', models.IntegerField()),
                ('avg_money', models.IntegerField()),
                ('Login_day_count', models.IntegerField()),
                ('Item_get_ratio', models.IntegerField()),
                ('playtime_per_day', models.IntegerField()),
                ('Exp_get_ratio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('all_user_count', models.BigIntegerField()),
                ('bot_user_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
